version: "3"

services:
  testsoftdesign:
    build: .
    container_name: testsoftdesign
    ports:
      - "3344:3344"
    volumes:
      - .:/home/node/app/
      - /home/node/app/node_modules
    environment:
      - APP_WEB_URL=https://rodociclo.com.br
      - APP_API_URL=https://test-softdesign.eadconcept.app.br
      - MAIL_DRIVER=smtp
      - MAIL_HOST=smtp.meudominio.com.br
      - MAIL_PORT=587
      - MAIL_SECURE=false
      - MAIL_USER=email@meudominio.com.br
      - MAIL_PASS=pass
    command: yarn start
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - testsoftdesign-network

networks:
  testsoftdesign-network:
    driver: bridge
